Repository home-assistant/iOS, pull requests merged in 2024-11, with the labels that each got.

#3123 Fix CarPlay icons and intro notification
  Sources/App/Notifications/NotificationManager.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessViewModel.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
  Sources/Shared/MagicItem/MagicItem.swift
  Sources/Shared/Notifications/NotificationIdentifier.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, CarPlay

#3124 Allow arbitrary load for web content and media
  Sources/App/Resources/Info.plist
Labels: cla-signed

#3125 Migrate watch and carplay config when serverID from items is unavailable
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/CarPlay/CarPlayConfig.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessViewModel.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/MagicItem/MagicItem+Migration.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Watch/WatchConfig.swift
  Tests/App/MagicItem/MagicItemProviderTests.swift
Labels: cla-signed, watch, CarPlay

#3126 Change sensor widget view
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
  Sources/Extensions/AppIntents/Widget/ReloadWidgetsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Extensions/Widgets/Sensor/WidgetSensors.swift
  Sources/Extensions/Widgets/Sensor/WidgetSensorsView.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3128 Remove actions from watch sync context
  Sources/Extensions/Watch/ExtensionDelegate.swift
Labels: cla-signed, watch

#3130 Add CarPlay config database validation test
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/CarPlay/CarPlayConfig.swift
  Tests/App/CarPlay/CarPlayConfig.test.swift
  Tests/App/CarPlay/CarPlayConfigV1.sqlite
  Tests/App/Watch/WatchConfig.test.swift
Labels: cla-signed, watch, CarPlay

#3131 Add tests for areas in CarPlay
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/CarPlay/Templates/Areas/AreaProvider.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Tests/App/Area/AreaProvider.test.swift
Labels: cla-signed, CarPlay

#3132 Bump App v2024.11
  Configuration/Version.xcconfig
Labels: cla-signed

#3145 Fix cover control state
  Sources/Extensions/Widgets/Cover/ControlCover.swift
  Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift
  Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
  Sources/Shared/ControlEntityProvider.swift
Labels: cla-signed, control-center

#3134 Allow entities on CarPlay quick access
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift
  Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift
  Sources/App/Settings/MagicItem/Add/MagicItemAddViewModel.swift
  Sources/App/Settings/MagicItem/Edit/MagicItemEditViewModel.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasZonesTemplate.swift
  Sources/CarPlay/Templates/CarPlayTemplateProvider.swift
  Sources/CarPlay/Templates/Domains/CarPlayDomainsListTemplate.swift
  Sources/CarPlay/Templates/Domains/CarPlayDomainsListViewModel.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListTemplate+Build.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListTemplate.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListViewModel.swift
  Sources/CarPlay/Templates/HAEntity+CarPlay.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayActionsTemplate+Build.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessViewModel.swift
  Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/Domain/Domain.swift
  Sources/Shared/MagicItem/MagicItem+Migration.swift
  Sources/Shared/MagicItem/MagicItem.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/App/MagicItem/MagicItemProviderTests.swift
Labels: cla-signed

#3147 Refresh controls when widgets initialize
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Shared/DataWidgetsUpdater.swift
Labels: cla-signed

#3148 Improve CarPlay areas load and add option to restart CarPlay
  Sources/App/AppEntitiesObserver.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/CarPlay/Templates/CarPlayPaginatedListTemplate.swift
  Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, CarPlay

#3149 Reflect CarPlay config changes in realtime
  Sources/App/AppEntitiesObserver.swift
  Sources/App/Assist/AssistViewModel.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/CarPlay/CarPlayConfig.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/ControlEntityProvider.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Watch/WatchConfig.swift
  Tests/App/MagicItem/MagicItemProviderTests.swift
Labels: cla-signed, CarPlay

#3152 Make webview inspectable for all builds
  Sources/App/WebView/WebViewController.swift
Labels: cla-signed

#3156 Fixes for CarPlay lag
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift
  Sources/CarPlay/Templates/Servers/CarPlayServerListViewModel.swift
Labels: cla-signed, CarPlay

#3157 Add download manager for WKWebView
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/DownloadManager/DownloadManagerView.swift
  Sources/App/WebView/DownloadManager/DownloadManagerViewModel.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3160 Update ci.yml - macOS-15 image
  .github/workflows/ci.yml
  .github/workflows/distribute.yml
  .github/workflows/download_localized_strings.yml
  fastlane/Fastfile
Labels: cla-signed

#3158 Improve download manager
  Sources/App/WebView/DownloadManager/DownloadManagerView.swift
  Sources/App/WebView/DownloadManager/DownloadManagerViewModel.swift
  Sources/Shared/Environment/AppConstants.swift
Labels: cla-signed

#3169 Making API connection optional given activeURL is now optional as well
  Sources/App/AppDelegate.swift
  Sources/App/AppEntitiesObserver.swift
  Sources/App/Notifications/NotificationManager.swift
  Sources/App/Onboarding/API/OnboardingAuth.swift
  Sources/App/Onboarding/API/Steps/OnboardingAuthStepDuplicate.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
  Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/App/Settings/Eureka/AccountRow.swift
  Sources/App/Settings/Eureka/TemplateSection.swift
  Sources/App/Settings/Observation/WidgetOpenPageIntent+Observation.swift
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementViewModel.swift
  Sources/App/Thread/CredentialsSharing/ToHomeAssistant/ThreadTransferCredentialToHAViewModel.swift
  Sources/App/Utilities/MenuManager.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/ZoneManager/ZoneManager.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListViewModel.swift
  Sources/CarPlay/Templates/HAEntity+CarPlay.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/Extensions/AppIntents/Action/PerformAction.swift
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/Matter/MatterRequestHandler.swift
  Sources/Extensions/NotificationContent/NotificationViewController.swift
  Sources/Extensions/NotificationService/NotificationService.swift
  Sources/Extensions/PushProvider/PushProvider.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Extensions/Watch/Notifications/DynamicNotificationController.swift
  Sources/Extensions/Widgets/Cover/CoverIntent.swift
  Sources/Extensions/Widgets/Light/LightIntent.swift
  Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
  Sources/Extensions/Widgets/Switch/SwitchIntent.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/API/Webhook/Networking/WebhookManager.swift
  Sources/Shared/ControlEntityProvider.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/Environment/ServerAlerter.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Sources/Shared/Intents/CallServiceIntentHandler.swift
  Sources/Shared/Intents/FireEventIntentHandler.swift
  Sources/Shared/Intents/GetCameraImageIntentHandler.swift
  Sources/Shared/Intents/PerformActionIntentHandler.swift
  Sources/Shared/Intents/RenderTemplateIntentHandler.swift
  Sources/Shared/Notifications/LocalPush/LocalPushManager.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/Shared/ModelManager.test.swift
  Tests/Shared/ServerAlerter.test.swift
Labels: cla-signed, connection

#3173 Fix cover control tint color and add option to define icon per state
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Cover/ControlCover.swift
  Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift
  Sources/Extensions/Widgets/Script/Control/SFSymbolEntity.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, control-center

#3175 Add icon specific for light control state
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift
  Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
Labels: cla-signed, control-center

#3177 simplify for loop
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
Labels: cla-signed

#3178 Use frontend discovery integration box for improv and native flow to co…
  Sources/App/Improv/ImprovDiscoverView.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalBusMessage.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/App/WebView/WebViewExternalBusMessageTests.swift
Labels: cla-signed, improv, bluetooth

#3172 Redesign Sensor widget
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/ActionConfigurator.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSensorView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewInterface.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewTintedWrapper.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Extensions/Widgets/Script/WidgetScripts.swift
  Sources/Extensions/Widgets/Sensor/WidgetSensors.swift
Labels: cla-signed

#3171 Prevent server deletion and inform user it is unauthenticated
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewWindowController.swift
  Sources/Shared/API/Authentication/TokenManager.swift
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/Environment/OnboardingStateObservation.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/Shared/ModelManager.test.swift
Labels: cla-signed, connection

#3180 Notify frontend when improv device setup is done
  Sources/App/Improv/ImprovDiscoverView.swift
  Sources/App/WebView/WebViewExternalBusMessage.swift
  Tests/App/WebView/WebViewExternalBusMessageTests.swift
Labels: cla-signed

#3181 Clean up download file on dismissing download manager
  Sources/App/WebView/DownloadManager/DownloadManagerView.swift
Labels: cla-signed

#3179 Unsubscribe model manager when in background
  Sources/App/AppDelegate.swift
  Sources/App/Scenes/WebViewSceneDelegate.swift
  Sources/Shared/API/Models/ModelManager.swift
Labels: cla-signed

#3182 Fix entities database sync
  Sources/Shared/API/Models/ModelManager.swift
Labels: cla-signed

#3184 Only notify frontend known improv devices
  Sources/App/WebView/WebViewExternalMessageHandler.swift
Labels: improv

#3185 Add extra logging for database updates
  Sources/Shared/API/Models/AppEntitiesModel.swift
Labels: cla-signed, database

#3197 Separate entities model cache per server
  Sources/Shared/API/Models/AppEntitiesModel.swift
Labels: cla-signed

#3198 Log when user requires internal URL setup
  Sources/App/ClientEvents/ClientEventTableViewController.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/Shared/API/ConnectionInfo.swift
  Sources/Shared/ClientEvents/Model/ClientEvent.swift
  Sources/Shared/ClientEvents/Model/ClientEventStore.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3203 Remove code not in use
  Sources/App/Assist/AssistViewModel.swift
Labels: cla-signed

#3204 Avoid executing watch item twice
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
Labels: cla-signed, watch

#3205 Reduce database updates throttling
  Sources/Shared/API/Models/AppEntitiesModel.swift
Labels: cla-signed

#3193 Revert "Allow arbitrary load for web content and media"
  Sources/App/Resources/Info.plist
Labels: cla-signed

#3207 Bump number of widgets allowed and refactor UI creation logic
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActionsProvider.swift
  Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSensorView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift
  Sources/Extensions/Widgets/Common/WidgetFamilySizes.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
  Tests/App/Widgets/WidgetsSizeTests.swift
Labels: cla-signed, widgets

#3206 Migrate client events list to SwiftUI and GRDB for database
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/ClientEvents/ClientEventCell.swift
  Sources/App/ClientEvents/ClientEventPayloadViewController.swift
  Sources/App/ClientEvents/ClientEventTableViewController.swift
  Sources/App/ClientEvents/ClientEvents.storyboard
  Sources/App/Resources/Scenes.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/ClientEventsLogView/ClientEventsLogView.swift
  Sources/App/Settings/ClientEventsLogView/ClientEventsLogViewModel.swift
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/API/Webhook/Networking/WebhookResponseServiceCall.swift
  Sources/Shared/ClientEvents/Model/ClientEvent.swift
  Sources/Shared/ClientEvents/Model/ClientEventStore.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/App/ZoneManager/ZoneManager.test.swift
  Tests/Shared/ClientEventTests.swift
  swiftgen.yml
Labels: cla-signed, database

#3211 Fix widget corner radius when size style compressed and preview them as tile card
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Common/TileCardStyleModifier.swift
  Sources/Extensions/Widgets/Common/WidgetBasicButtonView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSensorView.swift
  Sources/Extensions/Widgets/Common/WidgetFamilySizes.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
Labels: cla-signed, widget

#3212 Remove unused code left behind
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/Scenes.swift
  Sources/App/Resources/Segues.swift
Labels: cla-signed, scout

#3210 Observe client events changes in event log view
  Sources/App/Settings/ClientEventsLogView/ClientEventsLogView.swift
  Sources/App/Settings/ClientEventsLogView/ClientEventsLogViewModel.swift
Labels: cla-signed, database
