Repository home-assistant/iOS, pull requests merged in 2024-03, with the labels that each got.

#2618 Address deprecated call in `SettingDetailViewController`
  Sources/App/Settings/SettingsDetailViewController.swift
Labels: cla-signed

#2607 General maintenance on Permissions.swift
  Sources/App/Utilities/Permissions.swift
Labels: cla-signed

#2623 🧹 Remove unused `AuthorizationTests`
  HomeAssistant.xcodeproj/project.pbxproj
  Tests/Shared/AuthorizationTests.swift
Labels: cla-signed

#2625 🧹 Remove unused `queryDictionary`
  Sources/App/Utilities/NSURL+QueryDictionary.swift
Labels: cla-signed

#2621 Remove default `options` parameter
  Sources/App/Settings/Notifications/NotificationRateLimitsAPI.swift
  Sources/App/Settings/Notifications/NotificationSoundsViewController.swift
  Sources/App/Settings/Observation/NotificationCategory+Observation.swift
  Sources/App/Utilities/MenuManager.swift
  Sources/App/Utilities/UIColor+CSSRGB.swift
  Sources/App/Utilities/Utils.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/API/Authentication/AuthenticationAPI.swift
  Sources/Shared/API/Models/WatchComplication.swift
  Sources/Shared/API/Webhook/Networking/WebhookManager.swift
  Sources/Shared/Common/DiskCache.swift
  Sources/Shared/Common/Extensions/NSItemProvider+Additions.swift
  Sources/Shared/Common/Extensions/NSMutableAttributedString+Additions.swift
  Sources/Shared/Common/Extensions/Realm+Initialization.swift
  Sources/Shared/Common/Extensions/String+HA.swift
  Sources/Shared/Common/Extensions/Version+HA.swift
  Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
  Sources/Shared/Notifications/LocalPush/UserDefaultsValueSync.swift
  Tests/App/LocalizedStrings.test.swift
  Tests/Shared/Webhook/Promise+WebhookJson.test.swift
  Tests/Shared/Webhook/WebhookManager.test.swift
  Tests/UI/SnapshotHelper.swift
Labels: cla-signed

#2624 Swiftier code for `groupDir` check
  Sources/Shared/Environment/Constants.swift
Labels: cla-signed

#2617 Actions widget with background execution
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/AppIntents/IntentActionAppEntity.swift
  Sources/Extensions/AppIntents/PerformAction.swift
  Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Extensions/Widgets/Widgets.swift
Labels: cla-signed

#2622 Available checks cleanup for iOS 15 and watchOS 8
  Sources/App/Onboarding/API/OnboardingAuthLoginViewController.swift
  Sources/App/Servers/ServerSelectViewController.swift
  Sources/App/Thread/ThreadCredentialsSharing/ThreadClientService.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Extensions/Watch/ComplicationController.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/Models/NotificationAction.swift
  Sources/Shared/API/Models/WatchComplication.swift
  Sources/Shared/API/Webhook/Networking/WebhookResponseUpdateComplications.swift
  Sources/Shared/ClientEvents/Model/ClientEvent.swift
  Sources/Shared/Common/DiskCache.swift
  Sources/Shared/Common/Extensions/CLKComplication+Strings.swift
  Sources/Shared/Common/Extensions/CLLocation+Extensions.swift
  Sources/Shared/Common/ServerProviding.swift
  Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
  Sources/Shared/Environment/DeviceWrapper.swift
  Sources/Shared/Environment/FocusStatusWrapper.swift
  Sources/Shared/Intents/AssistIntentHandler.swift
  Sources/Shared/Intents/CallServiceIntentHandler.swift
  Sources/Shared/Intents/FireEventIntentHandler.swift
  Sources/Shared/Intents/FocusStatusIntentHandler.swift
  Sources/Shared/Intents/GetCameraImageIntentHandler.swift
  Sources/Shared/Intents/IntentHandlerFactory.swift
  Sources/Shared/Intents/OpenPageIntentHandler.swift
  Sources/Shared/Intents/PerformActionIntentHandler.swift
  Sources/Shared/Intents/RenderTemplateIntentHandler.swift
  Sources/Shared/Intents/SendLocationIntentHandler.swift
  Sources/Shared/Intents/UpdateSensorsIntentHandler.swift
  Sources/Shared/Intents/WidgetActionsIntentHandler.swift
  Sources/Shared/Location/CLLocation+Sanitize.swift
  Sources/Shared/Location/CLLocationManager+OneShotLocation.swift
  Sources/Shared/Notifications/LocalPush/LocalPushEvent.swift
  Sources/Vehicle/Templates/Actions/CarPlayActionsTemplate.swift
  Sources/Vehicle/Templates/HAEntity+CarPlay.swift
  Tests/Shared/LocalPushEvent.test.swift
Labels: cla-signed

#2627 Use only the Action real name (not identifier) when displaying in Car…
  Sources/Vehicle/Templates/Actions/CarPlayActionsTemplate.swift
Labels: cla-signed, CarPlay

#2626 Improvement for actions widget
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Labels: cla-signed, Widgets

#2629 Move thread credentials entry to debugging section
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/App/Settings/SettingsViewController.swift
Labels: cla-signed

#2631 Bump HAKit to 0.4
  Podfile
  Podfile.lock
Labels: cla-signed

#2632 Make project compile in Xcode 15.3
  HomeAssistant.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
Labels: cla-signed

#2636 Fix notification attachment issue
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/BarcodeScanner/Camera/BarcodeScannerCamera.swift
  Sources/App/BarcodeScanner/Camera/BarcodeScannerCameraView.swift
  Sources/App/BarcodeScanner/Camera/BarcodeScannerDataModel.swift
  Sources/App/BarcodeScanner/Camera/BarcodeScannerView.swift
  Sources/App/BarcodeScanner/Camera/BarcodeScannerViewModel.swift
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementView+Build.swift
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementView.swift
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementViewModel.swift
  Sources/App/Thread/CredentialsManagement/Views/ThreadCredentialDetailsView.swift
  Sources/App/Thread/CredentialsSharing/Tests/SimulatorThreadClientService.swift
  Sources/App/Thread/CredentialsSharing/Tests/ThreadCredentialsSharing.test.swift
  Sources/App/Thread/CredentialsSharing/Tests/ThreadCredentialsSharingViewModel.test.swift
  Sources/App/Thread/CredentialsSharing/ThreadCredentialsSharing+build.swift
  Sources/App/Thread/CredentialsSharing/ThreadCredentialsSharingView.swift
  Sources/App/Thread/CredentialsSharing/ThreadCredentialsSharingViewModelProtocol.swift
  Sources/App/Thread/CredentialsSharing/ToAppleKeychain/ThreadCredentialsSharingToKeychainViewModel.swift
  Sources/App/Thread/CredentialsSharing/ToHomeAssistant/ThreadTransferCredentialToHAViewModel.swift
  Sources/App/Thread/ThreadCredentialsSharing/ThreadClientService.swift
  Sources/Shared/Environment/MatterWrapper.swift
  Sources/Shared/Services/Thread/ThreadClientProtocol.swift
  Sources/Shared/Services/ThreadClientService.swift
Labels: bug, cla-signed

#2630 Localize migrated AppIntents
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/AppIntents/PerformAction.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2640 Add vibration when running widget from home screen
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
Labels: cla-signed

#2645 🚮 Remove unused `baseAction`
  Sources/Shared/API/Models/NotificationAction.swift
Labels: cla-signed

#2653 🧹 Remove unused `hexDescription`
  Sources/Shared/Common/Extensions/UIColor+CSS3+Hex.swift
Labels: cla-signed

#2654 Remove `settingsButton` optionality
  Sources/App/WebView/WebViewController.swift
Labels: cla-signed

#2658 Use a `switch` for `CMMotionActivityConfidence.description`
  Sources/Shared/Common/Extensions/CMMotion+StringExtensions.swift
Labels: cla-signed

#2660 Use latest changes from HAKit instead fetching from tag
  Podfile
  Podfile.lock
Labels: cla-signed

#2657 Fix `size` job running for forked repos
  .github/workflows/ci.yml
Labels: cla-signed

#2659 🧹 Remove unused `String` extension functions
  Sources/Shared/Common/Extensions/String+HA.swift
Labels: cla-signed

#2661 🔧 Fix deprecated `Data.init`
  Sources/Shared/Extensions/Data+Hexadecimal.swift
Labels: cla-signed

#2662 🧹 Remove unused `UIColor`-s
  Sources/Shared/Common/Extensions/UIColor+HA.swift
Labels: cla-signed

#2668 Bump app version 2024.4
  Configuration/Version.xcconfig
Labels: cla-signed

#2642 `static var` to `static let`
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Scenes/SceneManager.swift
  Sources/App/Scenes/WindowScenesManager.swift
  Sources/App/Scenes/WindowSizeObserver.swift
  Sources/App/Settings/SettingsViewController.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Extensions/AppIntents/IntentActionAppEntity.swift
  Sources/Extensions/AppIntents/PerformAction.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/MacBridge/MacBridgeNetworkMonitor.swift
  Sources/Shared/API/Fixtures/ServerFixture.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/MJPEGStreamer.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/API/Server.swift
  Sources/Shared/Common/ObjectMapperTransformers.swift
  Sources/Shared/Common/URLComponents+WidgetAuthenticity.swift
  Sources/Shared/Environment/Constants.swift
  Sources/Shared/Notifications/LocalPush/LocalPushManager.swift
  Sources/Shared/Notifications/LocalPush/PushProviderConfiguration.swift
  Sources/Shared/Notifications/UNNotificationContent+Additions.swift
  Sources/Vehicle/Templates/Servers/CarPlayServerListTemplate.swift
Labels: cla-signed

#2669 Avoid registering material design icons font several times
  Sources/Shared/Iconic/IconDrawable.swift
Labels: cla-signed
