Repository home-assistant/iOS, pull requests merged in 2024-10, with the labels that each got.

#3077 Update Version.xcconfig
  Configuration/Version.xcconfig
Labels: cla-signed, Hacktoberfest

#3078 Fix iPad onboarding where "manual address" is not presented
  Sources/App/Onboarding/Screens/OnboardingScanningViewController.swift
Labels: cla-signed, Hacktoberfest

#3097 Bump 2024.10
  Configuration/Version.xcconfig
Labels: cla-signed, Hacktoberfest

#3098 Avoid confirmation when running legacy iOS Action from Apple Watch
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
Labels: cla-signed, watch, Hacktoberfest

#3099 Mark some intents as legacy
  Sources/App/Resources/Base.lproj/Intents.intentdefinition
  Sources/App/Resources/Info.plist
  Sources/Extensions/Intents/Resources/Info.plist
  Sources/Shared/DataWidgetsUpdater.swift
Labels: cla-signed, Hacktoberfest, shortcuts

#3067 Sensor State Widget
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppEntitiesObserver.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/CarPlay/Templates/HAEntity+CarPlay.swift
  Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Sensor/WidgetSensors.swift
  Sources/Extensions/Widgets/Sensor/WidgetSensorsView.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/DataWidgetsUpdater.swift
  Sources/Shared/Domain/Domain.swift
  Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed, widgets

#3102 Group by server, widget selection order
  Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
Labels: cla-signed, Hacktoberfest

#3106 Use in app improv message
  Podfile
  Podfile.lock
  Sources/App/Notifications/NotificationManager.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Shared/Notifications/NotificationIdentifier.swift
Labels: cla-signed, Hacktoberfest

#3105 Respect frontend "start_listening" value when launching Assist
  Sources/App/WebView/WebViewExternalMessageHandler.swift
Labels: cla-signed, Hacktoberfest, assist

#3104 Add bluetooth permission screen
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Onboarding/Screens/Bluetooth/BluetoothPermissionView.swift
  Sources/App/Onboarding/Screens/Bluetooth/BluetoothPermissionViewModel.swift
  Sources/App/Onboarding/Screens/PermissionRequestView.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Shared/DesignSystem/Styles/HAButtonStyles.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Settings/SettingsStore.swift
Labels: cla-signed, Hacktoberfest

#3108 Preserve order getEntities function
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
  Sources/Extensions/Widgets/Light/IntentLightEntity.swift
  Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift
  Sources/Extensions/Widgets/Switch/IntentSwitchEntity.swift
  Sources/Shared/ControlEntityProvider.swift
Labels: cla-signed, Hacktoberfest

#3112 Add "reset app entities database" option in debug section
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, Hacktoberfest, debug

#3113 Fix Assist trigger from lovelace
  Sources/App/Assist/AssistViewModel.swift
Labels: cla-signed, Hacktoberfest, assist

#3114 Fix iOS controls state
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/Widgets/ControlRefreshDelay.swift
  Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
  Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift
Labels: cla-signed, Hacktoberfest, control-center

#3111 Add configuration screen for CarPlay, also migrate "iOS Actions" to "Quick access"
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/Assets.xcassets/carplay-logo.imageset/Contents.json
  Sources/App/Resources/Assets.xcassets/carplay-logo.imageset/carplay-logo.png
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/CarPlay/CarPlayConfig.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationViewModel.swift
  Sources/App/Settings/SettingsRootDataSource.swift
  Sources/App/Settings/SettingsViewController.swift
  Sources/CarPlay/Templates/Actions/CarPlayActionsTemplate+Build.swift
  Sources/CarPlay/Templates/Actions/CarPlayActionsTemplate.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/MaterialDesignIcons+CarPlay.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayActionsTemplate+Build.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessViewModel.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/HAAreaResponse.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Watch/WatchConfig.swift
Labels: cla-signed, Hacktoberfest, CarPlay
