Repository home-assistant/iOS, pull requests merged in 2024-07, with the labels that each got.

#2829 Add HA cloud badge to servers
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/Eureka/AccountRow.swift
  Sources/App/Utilities/Extensions/UIImage+Circle.swift
  Sources/Shared/Assets/Assets.swift
  Sources/Shared/Assets/SharedAssets.xcassets/ha-cloud-logo.imageset/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/ha-cloud-logo.imageset/ha-cloud-logo.pdf
Labels: cla-signed

#2825 Assist for Apple Watch
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/Assist/AssistChatItem.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/Watch/Assist/Settings/WatchAssistSettings.swift
  Sources/Extensions/Watch/Assist/Views/ChatBubbleView.swift
  Sources/Extensions/Watch/Assist/WatchAssistService.swift
  Sources/Extensions/Watch/Assist/WatchAssistView+Build.swift
  Sources/Extensions/Watch/Assist/WatchAssistView.swift
  Sources/Extensions/Watch/Assist/WatchAssistViewModel.swift
  Sources/Extensions/Watch/Assist/WatchAudioRecorder.swift
  Sources/Extensions/Watch/Complication/Assist/AssistDefaultComplication.swift
  Sources/Extensions/Watch/Complication/ComplicationController.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Sources/Extensions/Watch/HostingController.swift
  Sources/Extensions/Watch/Resources/Assets.xcassets/Complication.complicationset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/Complication.complicationset/Graphic Extra Large.imageset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/ha-logo-round.pdf
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/roundlogo-white.png
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/ha-logo-black (2).pdf
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/templatelogo.png
  Sources/Extensions/Watch/Resources/Info.plist
  Sources/Extensions/Watch/WatchCommunicatorService.swift
  Sources/Shared/Assets/Assets.swift
  Sources/Shared/Assets/SharedAssets.xcassets/casita-dark.imageset/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/casita-dark.imageset/casita-dark.png
  Sources/Shared/Assets/SharedAssets.xcassets/casita.imageset/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/casita.imageset/casita.png
  Sources/Shared/Assist/AssistChatItem.swift
  Sources/Shared/Intents/AssistInApp/AssistService.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Utilities/Color+ColorAsset.swift
  Sources/Shared/Watch/InteractiveImmediateMessages.swift
  Tests/App/Assist/Mocks/MockAssistService.swift
Labels: cla-signed

#2830 Add action widgets, open page widgets, and gauges on the Lock Screen
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/AppIntents/IntentServerAppEntitiy.swift
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Assist/WidgetAssistView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/Common/WidgetCircularView.swift
  Sources/Extensions/Widgets/Details/WidgetDetails.swift
  Sources/Extensions/Widgets/Details/WidgetDetailsView.swift
  Sources/Extensions/Widgets/Gauge/WidgetGauge.swift
  Sources/Extensions/Widgets/Gauge/WidgetGaugeView.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/PushServer/SharedPush/Sources/NotificationParserLegacy.swift
  Sources/Shared/Common/AppIntentWidgetKinds.swift
  Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2838 Add device registry id to assist call
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/Responses/ConfigResponse.swift
  Sources/Shared/API/Server.swift
  Sources/Shared/Intents/AssistInApp/AssistRequests.swift
  Sources/Shared/Intents/AssistInApp/AssistService.swift
Labels: cla-signed

#2839 Improvements for Apple Watch Assist
  Sources/App/Assist/AssistViewModel.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/Watch/Assist/Settings/WatchAssistSettings.swift
  Sources/Extensions/Watch/Assist/WatchAssistService.swift
  Sources/Extensions/Watch/Assist/WatchAssistView+Build.swift
  Sources/Extensions/Watch/Assist/WatchAssistView.swift
  Sources/Extensions/Watch/Assist/WatchAssistViewModel.swift
  Sources/Extensions/Watch/Assist/WatchAudioRecorder.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Sources/Extensions/Watch/HostingController.swift
  Sources/Extensions/Watch/WatchCommunicatorService.swift
  Sources/Shared/Intents/AssistInApp/AssistModel.swift
  Sources/Shared/Intents/AssistInApp/AssistRequests.swift
  Sources/Shared/Intents/AssistInApp/AssistService.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Watch/InteractiveImmediateMessages.swift
Labels: cla-signed, watch, Assist

#2849 Scout external message handler
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/BarcodeScanner/Camera/BarcodeScannerViewModel.swift
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Tests/App/WebView/Mocks/MockWebViewController.swift
  Tests/App/WebView/WebViewExternalMessageHandlerTests.swift
Labels: cla-signed, scout

#2852 Redesign widgets to align with HA tiles UI
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/App/Settings/ActionConfigurator.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Extensions/Widgets/Assist/WidgetAssistView.swift
  Sources/Extensions/Widgets/Common/WidgetBackground.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Extensions/Widgets/Widgets.swift
Labels: cla-signed, widgets

#2858 Update widget UI to align with frontend
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Shared/Assets/Assets.swift
  Sources/Shared/Assets/Colors.xcassets/Background/Contents.json
  Sources/Shared/Assets/Colors.xcassets/Background/primaryBackground.colorset/Contents.json
  Sources/Shared/Assets/Colors.xcassets/Background/tileBackground.colorset/Contents.json
  Sources/Shared/Assets/Colors.xcassets/Border/Contents.json
  Sources/Shared/Assets/Colors.xcassets/Border/tileBorder.colorset/Contents.json
Labels: cla-signed

#2859 Bump Improv 0.0.6
  Podfile
  Podfile.lock
Labels: cla-signed

#2860 Remove custom toast and notify Improv via notification
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Improv/ImprovDiscoverView.swift
  Sources/App/Notifications/NotificationIdentifier.swift
  Sources/App/Notifications/NotificationManager.swift
  Sources/App/Utilities/LocalNotificationDispatcher.swift
  Sources/App/WebView/Views/WebViewAccessoryViews.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalMessageHandler+Build.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Shared/DesignSystem/Components/AppleLikeBottomSheet.swift
  Tests/App/WebView/Mocks/MockLocalNotificationDispatcher.swift
  Tests/App/WebView/WebViewExternalMessageHandlerTests.swift
Labels: cla-signed

#2861 Allow 2 items in systemSmall widget + update Apple Watch item style
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
Labels: cla-signed

#2862 Improve widgets structure and add AppIntent to reload it's timelines
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/Info.plist
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Observation/Action+Observation.swift
  Sources/App/Settings/Observation/WidgetOpenPageIntent+Observation.swift
  Sources/Extensions/AppIntents/Action/IntentActionAppEntity.swift
  Sources/Extensions/AppIntents/Action/PerformAction.swift
  Sources/Extensions/AppIntents/Widget/ReloadWidgetsAppIntent.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Assist/WidgetAssist.swift
  Sources/Extensions/Widgets/Details/WidgetDetails.swift
  Sources/Extensions/Widgets/Gauge/WidgetGauge.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Shared/Common/AppIntentWidgetKinds.swift
  Sources/Shared/Common/SiriIntents+ConvenienceInits.swift
  Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed, widgets

#2863 Simplify widgets and small UI tweaks
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/App/Resources/Base.lproj/Intents.intentdefinition
  Sources/App/Settings/ActionConfigurator.swift
  Sources/Extensions/AppIntents/WidgetActionsAppIntent.swift
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicSizeStyle.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPage.swift
  Sources/Shared/DesignSystem/Constants/Spaces.swift
Labels: cla-signed

#2867 Bump 2024.8
  Configuration/Version.xcconfig
Labels: cla-signed

#2864 Remove old Today's view widget
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/Today/Resources/Info.plist
  Sources/Extensions/Today/TodayViewController.swift
Labels: cla-signed

#2865 Detect SSID on watch to decide which endpoint to use to run actions
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Sources/Shared/Environment/ConnectivityWrapper.swift
  Sources/Shared/Environment/WatchUserDefaults.swift
Labels: cla-signed

#2868 Fix issue where notification URL closes app right away
  Sources/App/Scenes/SceneManager.swift
Labels: cla-signed

#2871 Remove "today's view" target from podfile
  Podfile
  Podfile.lock
Labels: cla-signed

#2878 Update watch placeholder logo
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/ha-logo-watch.png
  Sources/Extensions/Watch/Resources/Assets.xcassets/RoundLogo.imageset/roundlogo-white.png
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/Contents.json
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/ha-logo-watch.png
  Sources/Extensions/Watch/Resources/Assets.xcassets/TemplateLogo.imageset/templatelogo.png
Labels: cla-signed, watch

#2879 Fix Open Page widget selection bug
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
Labels: cla-signed, widgets

#2880 Add Actions custom colors back
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/ActionConfigurator.swift
  Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Sources/Extensions/Widgets/Actions/WidgetActions.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Shared/API/Models/Action.swift
  Sources/Shared/API/Responses/MobileAppConfig/MobileAppConfigAction.swift
  Sources/Shared/Common/Extensions/Realm+Initialization.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, watch, widgets

#2882 Scout - Remove lock screen widgets force unwrap
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Details/WidgetDetails.swift
  Sources/Extensions/Widgets/Gauge/WidgetGauge.swift
Labels: cla-signed

#2886 Fix watch crash (Realm migration not called)
  Sources/Extensions/Watch/Complication/ComplicationController.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Extensions/Watch/Home/Views/WatchActionButtonView.swift
  Sources/Shared/API/Models/Action.swift
  Sources/Shared/Common/Extensions/Realm+Initialization.swift
Labels: cla-signed, watch
