Repository home-assistant/iOS, pull requests merged in 2024-12, with the labels that each got.

#3217 Replace precondition by log for deleted servers check
  Sources/Shared/API/ServerManager.swift
Labels: cla-signed, crash

#3218 Prevent AppEntities auto init in extensions
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/Environment/Environment.swift
Labels: cla-signed, crash

#3219 Add "no url available" warning
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3161 iOS Audio output sensor
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Shared/API/Webhook/Sensors/AudioOutputSensor.swift
  Sources/Shared/Environment/Environment.swift
Labels: cla-signed, sensor

#3223 Change sensor widget placeholder
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
Labels: cla-signed

#3221 Add "Mac native features only" experimental mode
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/HAApplicationShortcutItem.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/WebViewSceneDelegate.swift
  Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
  Sources/App/Settings/Observation/Action+Observation.swift
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Settings/SettingsStore.swift
Labels: cla-signed

#3225 Remove fatal error for GRDB database creation
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
Labels: cla-signed

#3226 Add missing strings for mac native features only mode
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3227 Increase "location too old" time
  Sources/App/ZoneManager/ZoneManagerProcessor.swift
  Tests/App/ZoneManager/ZoneManagerProcessor.test.swift
Labels: cla-signed

#3154 Subscribe only to domains that the app has usage for
  Podfile
  Podfile.lock
  Sources/App/AppEntitiesObserver.swift
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/Eureka/AccountRow.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/HAEntity+CarPlay.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/API/WebSocket/HAPanel.swift
  Sources/Shared/Domain/Domain.swift
  Sources/Shared/Environment/AppConstants.swift
  Sources/Shared/Intents/GetCameraImageIntentHandler.swift
Labels: cla-signed

#3229 Add person domain to states subscription
  Sources/CarPlay/Templates/HAEntity+CarPlay.swift
  Sources/Shared/API/Models/ModelManager.swift
  Sources/Shared/Domain/Domain.swift
Labels: cla-signed

#3231 Periodic update app entities instead of subscribing to state updates
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Scenes/WebViewSceneDelegate.swift
  Sources/App/Settings/SettingsViewController.swift
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/API/Models/LegacyModelManager.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
  Sources/Shared/HATypedRequest+App.swift
  Tests/App/Auth/OnboardingAuthStepModels.test.swift
  Tests/App/Auth/OnboardingAuthStepNotify.test.swift
  Tests/Shared/ModelManager.test.swift
Labels: cla-signed, database

#3236 Improv CarPlay states subscription
  Podfile
  Podfile.lock
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasZonesTemplate.swift
Labels: cla-signed, CarPlay

#3237 Rename iOS audio sensor values
  Sources/Shared/API/Webhook/Sensors/AudioOutputSensor.swift
Labels: cla-signed, sensor

#3238 Add customizable gestures
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Gestures/AppleLikeListTopRowHeader.swift
  Sources/App/Settings/Gestures/GesturesSetupView.swift
  Sources/App/Settings/Gestures/GesturesSetupViewModel.swift
  Sources/App/Settings/SettingsRootDataSource.swift
  Sources/App/Settings/SettingsViewController.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewWindowController.swift
  Sources/Shared/HAGesture.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Settings/SettingsStore.swift
Labels: cla-signed

#3239 Fix swipe direction and comment gestures that are not working well yet
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/HAGesture.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3242 Allow choosing pipeline when using Assist shortcut
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/Base.lproj/Intents.intentdefinition
  Sources/Shared/Common/Locale+IntentLanguage.swift
  Sources/Shared/Intents/AssistIntentHandler.swift
Labels: cla-signed, assist, shortcuts, WTH

#3245 Fix legacy intents names
  Sources/App/Resources/Base.lproj/Intents.intentdefinition
Labels: cla-signed

#3248 Subscribe to quick access entity changes on top of the standard CarPlay subscription
  Sources/App/Scenes/CarPlaySceneDelegate.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasViewModel.swift
  Sources/CarPlay/Templates/Areas/CarPlayAreasZonesTemplate.swift
  Sources/CarPlay/Templates/CarPlayTemplateProvider.swift
  Sources/CarPlay/Templates/Domains/CarPlayDomainsListTemplate.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListTemplate.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntitiesListViewModel.swift
  Sources/CarPlay/Templates/Entities/CarPlayEntityListItem.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/CarPlay/Templates/Servers/CarPlayServerListTemplate.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
Labels: cla-signed, CarPlay

#3250 Add Assist typing indicator
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Assist/AssistTypingIndicator.swift
  Sources/App/Assist/AssistView.swift
  Sources/App/Assist/AssistViewModel.swift
  Sources/Extensions/Watch/Assist/Views/ChatBubbleView.swift
  Sources/Shared/Assist/AssistChatItem.swift
Labels: cla-signed, assist

#3251 Rename actions to "(Legacy) iOS Actions" and move it down on the list
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/App/Settings/SettingsRootDataSource.swift
  Sources/App/Settings/SettingsViewController.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3253 Remove URL path in onboarding to avoid wrong redirect after login
  Sources/App/Onboarding/Screens/OnboardingManualURLViewController.swift
Labels: cla-signed, onboarding

#3254 Bump 2024.12.1
  Configuration/Version.xcconfig
Labels: cla-signed

#3257 Improv database table creation logs
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
Labels: database

#3258 Request App Store review after saving watch and carplay configuration
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/CarPlay/CarPlayConfigurationView.swift
Labels: cla-signed

#3260 Add option to always fallback to internal URL
  Sources/App/Onboarding/API/OnboardingAuth.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
  Sources/App/Settings/Connection/ConnectionURLViewController.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/API/ConnectionInfo.swift
  Sources/Shared/API/Fixtures/ServerFixture.swift
  Sources/Shared/API/Server+Fakes.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/Shared/ConnectionInfo.test.swift
  Tests/Shared/ServerManager.test.swift
  Tests/Shared/Webhook/WebhookManager.test.swift
Labels: cla-signed, connection

#3261 Add missing CarPlay-used domains to app database sync
  Sources/Shared/API/Models/AppEntitiesModel.swift
Labels: cla-signed, CarPlay, database

#3267 Warning when internal URL requires more permissions before it can be used
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Onboarding/API/OnboardingAuth.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Connection/ConnectionURLViewController.swift
  Sources/App/WebView/NoActiveURLView.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/DesignSystem/Styles/HAButtonStyles.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, connection

#3268 Cache config/entity_registry/list_for_display
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/EntityRegistryListForDisplay.swift
  Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
  Sources/Shared/HATypedRequest+App.swift
Labels: cla-signed, database

#3270 Add more domains for sensors widget
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Sensor/IntentSensorsAppEntity.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsConfig.swift
  Sources/Extensions/Widgets/Cover/ControlCoverValueProvider.swift
  Sources/Extensions/Widgets/Cover/IntentCoverEntity.swift
  Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
  Sources/Extensions/Widgets/Light/IntentLightEntity.swift
  Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift
  Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift
  Sources/Extensions/Widgets/Switch/IntentSwitchEntity.swift
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/ControlEntityProvider.swift
Labels: cla-signed, widgets, database

#3269 Use correct sensor precision in sensors widget
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
  Sources/Shared/EntityRegistryListForDisplay.swift
Labels: cla-signed, widgets

#3271 Bump 2024.12.2
  Configuration/Version.xcconfig
Labels: cla-signed

#3274 Add new connection error explanation screen
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/Assets.xcassets/CustomSymbols/discord.fill.symbolset/Contents.json
  Sources/App/Resources/Assets.xcassets/CustomSymbols/discord.fill.symbolset/discord.fill.svg
  Sources/App/Resources/Assets.xcassets/CustomSymbols/github.fill.symbolset/Contents.json
  Sources/App/Resources/Assets.xcassets/CustomSymbols/github.fill.symbolset/github.fill.svg
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/ConnectionErrorDetailsView.swift
  Sources/App/WebView/NoActiveURLView.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/DesignSystem/Components/ExternalLinkButton.swift
  Sources/Shared/DesignSystem/Components/SheetCloseButton.swift
  Sources/Shared/ExternalLink.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, connection

#3276 Fallback to internal URL until location enforcement is communicated c…
  Sources/App/Settings/Connection/ConnectionSettingsViewController.swift
  Sources/App/Settings/Connection/ConnectionURLViewController.swift
  Sources/Shared/API/ConnectionInfo.swift
  Tests/Shared/ConnectionInfo.test.swift
Labels: cla-signed, connection

#3277 Delete old panels from database
  Sources/Shared/Panels/PanelsUpdater.swift
Labels: cla-signed, database

#3278 Update Open page widget items limit and sensor capitalized state
  Sources/App/Resources/Base.lproj/Intents.intentdefinition
  Sources/Extensions/AppIntents/Widget/Sensor/WidgetSensorsAppIntentTimelineProvider.swift
Labels: cla-signed, widgets

#3281 Avoid unecessary subscription while fetching user avatar
  Sources/App/Settings/Eureka/AccountRow.swift
Labels: cla-signed

#3282 Reduce minimum core version for subscription with filter
  Sources/Shared/Environment/AppConstants.swift
Labels: cla-signed, connection

#3283 Improve logs for entities model updater
  Sources/Shared/API/Models/AppEntitiesModel.swift
  Sources/Shared/Environment/PeriodicAppEntitiesModelUpdater.swift
Labels: cla-signed, database

#3285 Fix typo "Github" in Localizable.strings
  Sources/App/Resources/en.lproj/Localizable.strings
Labels: cla-signed

#3291 Bump 2024.12.3
  Configuration/Version.xcconfig
Labels: cla-signed

#3293 Remove trailing space from copy
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Watch/Assist/WatchAssistView.swift
Labels: cla-signed

#3295 Auto open share sheet after download
  Sources/App/WebView/DownloadManager/DownloadManagerView.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed
