Repository home-assistant/iOS, pull requests merged in 2024-08, with the labels that each got.

#2893 Use Apple Vision Pro and visionOS instead of iPad as name
  Sources/Shared/Environment/DeviceWrapper.swift
Labels: cla-signed

#2895 Remove unused environment key in WidgetOpenPage
  Sources/Extensions/Widgets/OpenPage/WidgetOpenPageProvider.swift
Labels: cla-signed

#2892 Add location permission sensor
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Shared/API/Webhook/Sensors/LocationPermissionSensor.swift
  Sources/Shared/Environment/Environment.swift
Labels: cla-signed, sensor

#2896 Add App version sensor
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Shared/API/Webhook/Sensors/AppVersionSensor.swift
  Sources/Shared/Environment/Environment.swift
Labels: cla-signed, sensor

#2897 Add Apple Watch battery sensor
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Extensions/Watch/Home/Mocks/MockWatchHomeViewModel.swift
  Sources/Shared/API/WatchHelpers.swift
  Sources/Shared/API/Webhook/Sensors/BatterySensor.swift
  Sources/Shared/API/Webhook/Sensors/WatchBatterySensor.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/Location/LocationTrigger.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Tests/App/Watch/WatchContextTests.swift
Labels: cla-signed, sensor, watch

#2899 Use entity category "diagnostic" for App Version
  Sources/Shared/API/Models/WebhookSensor.swift
  Sources/Shared/API/Webhook/Sensors/AppVersionSensor.swift
Labels: cla-signed

#2900 Add "Run Script" AppIntent and Widget
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/App/AppDelegate.swift
  Sources/App/Resources/Info.plist
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/ScriptsObserver.swift
  Sources/App/WebView/WebViewExternalMessageHandler+Build.swift
  Sources/Extensions/AppIntents/Action/IntentActionAppEntity.swift
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/Intents/Resources/Info.plist
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Extensions/Widgets/Script/WidgetScripts.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/API/WebSocket/HAScripts.swift
  Sources/Shared/Notifications/LocalNotificationDispatcher.swift
  Sources/Shared/Notifications/NotificationIdentifier.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/WebView/Mocks/MockLocalNotificationDispatcher.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed

#2910 Add sharedEventDeviceInfo data into the "tag_scanned" event
  Sources/Shared/API/HAAPI.swift
Labels: cla-signed

#2906 Retry with activeURL when cloud hook returns 503
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/API/Webhook/Networking/Promise+WebhookJson.swift
  Sources/Shared/API/Webhook/Networking/WebhookManager.swift
  Tests/Shared/Webhook/Promise+WebhookJson.test.swift
Labels: cla-signed, cloud

#2915 Log event when retrying 503 webhook error
  Sources/Shared/API/Webhook/Networking/WebhookManager.swift
Labels: cla-signed

#2918 Use mobile web content for iPad and desktop for mac
  Sources/App/WebView/WebViewController.swift
Labels: cla-signed

#2919 Workaround to avoid iOS 18 crash widgets that use Realm
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/Extensions/AppIntents/Widget/Actions/WidgetActionsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Actions/WidgetActionsProvider.swift
Labels: cla-signed

#2920 Add scripts widget suggestions and avoid requiring confirmation when running several scripts at once
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
Labels: cla-signed

#2924 Use app header color for older HA core versions
  Sources/App/Utilities/ThemeColors.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/Environment/Constants.swift
Labels: cla-signed

#2932 Bump 2024.8.1
  Configuration/Version.xcconfig
Labels: cla-signed

#2940 Fix Action widget haptics
  Sources/Extensions/AppIntents/Action/PerformAction.swift
Labels: cla-signed

#2942 Fix gauge and details widget checked continuation
  Sources/Extensions/AppIntents/Widget/Details/WidgetDetailsAppIntentTimelineProvider.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
Labels: cla-signed

#2941 Add missing localization keys for AssistInApp intent definition
  Sources/App/Resources/en.lproj/Intents.strings
Labels: cla-signed

#2934 New gauge widget variant; fix leaked continuation
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Gauge/WidgetGaugeAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Gauge/WidgetGaugeView.swift
Labels: cla-signed

#2947 Bump 2024.9
  Configuration/Version.xcconfig
Labels: cla-signed

#2923 Add iOS 18 icons and update pipeline
  .github/workflows/ci.yml
  .github/workflows/distribute.yml
  Gemfile
  Gemfile.lock
  Sources/App/Resources/Assets.xcassets/AlternateIcons/beta.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/beta.appiconset/Icon-Dark-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/beta.appiconset/Icon-Tinted-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/white.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/white.appiconset/Icon-Dark-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/white.appiconset/Icon-Tinted-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Dark-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Tinted-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.beta.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AppIcon.beta.appiconset/Icon-Dark-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.beta.appiconset/Icon-Tinted-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.dev.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AppIcon.dev.appiconset/Icon-Dark-1024x1024.png
  Sources/App/Resources/Assets.xcassets/AppIcon.dev.appiconset/Icon-Tinted-1024x1024.png
  fastlane/Fastfile
Labels: cla-signed

#2949 Fix variable WidgetBundle, fix iOS 15 and 16 widgets
  Sources/Extensions/Widgets/Widgets.swift
Labels: cla-signed

#2945 add charging state sensor for Apple Watch
  Sources/Shared/API/WatchHelpers.swift
  Sources/Shared/API/Webhook/Sensors/WatchBatterySensor.swift
  Tests/App/Watch/WatchContextTests.swift
Labels: cla-signed

#2950 Fix watch empty state and reposition reload button for watchOS 10
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift
  Sources/Extensions/Watch/Home/WatchHomeCoordinatorViewModel.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
Labels: cla-signed

#2952 Add "Script" iOS 18 ControlWidget
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Podfile
  Podfile.lock
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Script/Control/ControlScript.swift
  Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
  Sources/Extensions/Widgets/Script/Control/SFSymbolEntity.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed

#2956 Remove import SharedPush from SPM and import it manually
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/SharedPush/Package.swift
  Sources/SharedPush/Sources/NotificationParserLegacy.swift
Labels: cla-signed

#2957 Add assist volume control back to watch
  Sources/Extensions/Watch/Assist/WatchAssistView.swift
  Sources/Extensions/Watch/Assist/WatchAssistViewModel.swift
Labels: cla-signed

#2960 Update CI to use Xcode 16 instead of 16.1
  .github/workflows/ci.yml
  .github/workflows/distribute.yml
Labels: cla-signed

#2961 Improve symbols search and add name to script control widget
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Script/Control/ControlScript.swift
  Sources/Extensions/Widgets/Script/Control/SFSymbolEntity.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2962 Watch configuration improvements
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
  Sources/Shared/MagicItem/MagicItem.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed
