Repository home-assistant/iOS, pull requests merged in 2024-09, with the labels that each got.

#2966 Fix watch sensors sync
  Sources/App/Settings/Observation/Action+Observation.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/Shared/API/WatchHelpers.swift
  Sources/Shared/API/Webhook/Sensors/WatchBatterySensor.swift
Labels: cla-signed

#2967 Define dark and tinted variants for some custom icons
  Sources/App/Resources/Assets.xcassets/AlternateIcons/POC_pride.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/POC_pride.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/beta.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/beta.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/bi_pride.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/bi_pride.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/black.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/black.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/dev.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/dev.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/non-binary.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/non-binary.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/rainbow.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/rainbow.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AlternateIcons/trans.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AlternateIcons/trans.appiconset/Icon-Tinted-1024x1-24.png
  Sources/App/Resources/Assets.xcassets/AppIcon.dev.appiconset/Contents.json
  Sources/App/Resources/Assets.xcassets/AppIcon.dev.appiconset/Icon-Dark-1024x1024.png
Labels: cla-signed

#2970 Fix iOS 18 controls notification when run
  Sources/Extensions/Widgets/Scene/Control/ControlScene.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift
  Sources/Extensions/Widgets/Script/Control/ControlScript.swift
  Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
Labels: cla-signed

#2972 iOS18 Assist control
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Widgets.xcscheme
  Sources/App/Resources/Assets.xcassets/Contents.json
  Sources/App/Resources/Assets.xcassets/CustomSymbols/Contents.json
  Sources/App/Resources/Assets.xcassets/CustomSymbols/message-processing-outline.symbolset/Contents.json
  Sources/App/Resources/Assets.xcassets/CustomSymbols/message-processing-outline.symbolset/message-processing-outline.svg
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Assist/AssistAppIntent.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssist.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift
  Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/Assets/Assets.swift
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/message-processing-outline.symbolset/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/message-processing-outline.symbolset/message-processing-outline.svg
  Sources/Shared/Environment/AppConstants.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistInAppIntentHandler.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistRequests.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed

#2974 Move watch item run logic from home to item row
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Tests/App/Watch/WatchContext.test.swift
Labels: cla-signed

#2975 Add iOS 18 Open Page Control
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPage.swift
  Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPageValueProvider.swift
  Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
  Sources/Extensions/Widgets/OpenPage/PageAppEntity.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/API/WebSocket/HAPanel.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed

#2980 Update Control Assist copy
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Assist/Control/ControlAssist.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2979 Update text from iOS 18 controls
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Assist/AssistAppIntent.swift
  Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2981 Replace caches by separate database for entities which domains relate to app usage
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/AppEntitiesObserver.swift
  Sources/App/ScenesObserver.swift
  Sources/App/ScriptsObserver.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationViewModel.swift
  Sources/App/Settings/DebugSettingsViewController.swift
  Sources/App/Settings/MagicItem/Add/MagicItemAddView.swift
  Sources/App/Settings/MagicItem/Add/MagicItemAddViewModel.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
  Sources/Extensions/Watch/Home/WatchHomeViewModel.swift
  Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift
  Sources/Extensions/Widgets/Script/WidgetScripts.swift
  Sources/Shared/API/WebSocket/HAScene.swift
  Sources/Shared/API/WebSocket/HAScript.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/Common/Extensions/GRDBWatchConfig+Initialization.swift
  Sources/Shared/Common/Extensions/XCGLogger+Export.swift
  Sources/Shared/Environment/AppConstants.swift
  Sources/Shared/Environment/Environment.swift
  Sources/Shared/HAAppEntity.swift
  Sources/Shared/MagicItem/MagicItem.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#2986 Ask watch to update context when iOS background fetch happens
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/Extensions/Watch/ExtensionDelegate.swift
  Sources/Shared/Watch/GuaranteedMessages.swift
Labels: cla-signed

#2987 Add iOS 18 ControlLight
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/Widgets/Light/ControlLight.swift
  Sources/Extensions/Widgets/Light/ControlLightsValueProvider.swift
  Sources/Extensions/Widgets/Light/IntentLightEntity.swift
  Sources/Extensions/Widgets/Light/LightIntent.swift
  Sources/Extensions/Widgets/Widgets.swift
  Sources/Shared/HAAreaResponse.swift
  Sources/Shared/HATypedRequest+App.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Widget/WidgetsKind.swift
  Tests/App/Widgets/WidgetsKindTests.swift
Labels: cla-signed

#2992 Use Assist pipelines cache value to avoid overload and delays on widgets extension
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/SceneManager.swift
  Sources/Extensions/Widgets/Assist/AssistAppIntent.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssist.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
  Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScene.swift
  Sources/Extensions/Widgets/Script/Control/ControlScript.swift
  Sources/Shared/Assets/Assets.swift
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/message-processing-outline.symbolset/Contents.json
  Sources/Shared/Assets/SharedAssets.xcassets/CustomSymbols/message-processing-outline.symbolset/message-processing-outline.svg
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, widgets

#2996 Present Assist UI faster when it comes from app extensions
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Extensions/Widgets/Assist/AssistAppIntent.swift
  Tests/App/WebView/Mocks/MockWebViewController.swift
Labels: cla-signed, assist

#2997 Update GRDB to avoid intermitent crash
  Podfile
  Podfile.lock
Labels: cla-signed

#3001 Bump app version 2024.9.1
  Configuration/Version.xcconfig
Labels: cla-signed

#3002 Avoid updating database in background
  Sources/App/AppEntitiesObserver.swift
Labels: cla-signed

#3008 Fix tinted widgets in iOS 18
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/ActionConfigurator.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewTintedWrapper.swift
Labels: cla-signed

#3009 Display Assist for older watchOS
  Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift
  Sources/Extensions/Watch/Home/WatchHomeView.swift
Labels: cla-signed

#3007 Fix control scene id when calling to activate scene
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntentTimelineProvider.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
  Sources/Extensions/Widgets/Common/WidgetBasicViewModel.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScene.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift
  Sources/Extensions/Widgets/Scene/Control/IntentSceneEntity.swift
  Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
  Sources/Extensions/Widgets/Script/Control/ControlScript.swift
  Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
  Sources/Extensions/Widgets/Script/WidgetScripts.swift
Labels: cla-signed

#3003 Improv-BLE UX updates
  Sources/App/Improv/ImprovDiscoverView.swift
Labels: cla-signed

#3014 Fix Apple Watch text color and dynamic type
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
Labels: cla-signed

#3015 Bump app version 2024.9.2
  Configuration/Version.xcconfig
Labels: cla-signed

#3019 Add option to delete thread network credential from Apple Keychain
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementView.swift
  Sources/App/Thread/CredentialsManagement/ThreadCredentialsManagementViewModel.swift
  Sources/App/WebView/WebViewController.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Services/Thread/ThreadClientProtocol.swift
  Sources/Shared/Services/ThreadClientService.swift
  Tests/App/Thread/CredentialsSharing/SimulatorThreadClientService.swift
Labels: cla-signed, thread

#3017 Add "Preferred" pipeline to Control Assist
  Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
Labels: cla-signed, assist

#3018 Add double tap watch gesture to launch Assist
  Sources/Extensions/Watch/Assist/WatchAssistView.swift
  Sources/Extensions/Watch/Home/WatchHomeCoordinatorView.swift
Labels: cla-signed, watch

#3024 Fix Assist and Open page iOS 18 controls to have default action and u…
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/AppDelegate.swift
  Sources/App/BarcodeScanner/DataWidgetsUpdater.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Scenes/WebViewSceneDelegate.swift
  Sources/Extensions/Widgets/Assist/AssistAppIntent.swift
  Sources/Extensions/Widgets/Assist/Control/ControlAssistValueProvider.swift
  Sources/Extensions/Widgets/OpenPage/OpenPageAppIntent.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, control-center

#3026 Use cached assist pipelines to speed up starting command
  Sources/App/Assist/AssistViewModel.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Tests/App/Assist/AssistViewModel.test.swift
Labels: cla-signed, assist

#3028 Update 'confirmation notification' copy
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/AppIntents/Widget/Script/WidgetScriptsAppIntent.swift
  Sources/Extensions/Widgets/OpenPage/Control/ControlOpenPageValueProvider.swift
  Sources/Extensions/Widgets/Scene/Control/ControlScenesValueProvider.swift
  Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
  Sources/Extensions/Widgets/Script/Control/ControlScriptsValueProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3029 Fix scene icons not showing on Apple Watch
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/AppleWatch/HomeCustomization/WatchConfigurationView.swift
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
  Sources/Shared/MagicItem/MagicItemProvider.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, watch

#3040 Fix watch configuration colors setup
  Podfile.lock
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
  Sources/Shared/MagicItem/MagicItem.swift
Labels: cla-signed, watch

#3044 Fix remaining tinted widgets
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/Extensions/Widgets/Assist/WidgetAssist.swift
  Sources/Extensions/Widgets/Assist/WidgetAssistView.swift
  Sources/Extensions/Widgets/Assist/WidgetAssistViewTintedWrapper.swift
  Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
Labels: cla-signed, widgets

#3027 Use home assistant defined thread network when commissioning matter device
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/Extensions-Matter.xcscheme
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Extensions/Matter/MatterRequestHandler.swift
  Sources/Shared/Environment/MatterWrapper.swift
  Sources/Shared/Extensions/Data+Hexadecimal.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
  Sources/Shared/Services/ThreadClientService.swift
  Sources/Shared/Settings/SettingsStore.swift
  Tests/App/WebView/Mocks/MockWebViewController.swift
Labels: cla-signed

#3047 Bump 2024.9.3
  Configuration/Version.xcconfig
Labels: cla-signed

#3050 Always present controllers in main thread (fix Matter issue)
  Sources/App/WebView/WebViewController.swift
Labels: cla-signed

#3052 Update onboarding with modern HA design
  HomeAssistant.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Sources/App/Onboarding/API/OnboardingAuth.swift
  Sources/App/Onboarding/Container/OnboardingNavigationViewController.swift
  Sources/App/Onboarding/Screens/ActivityView.swift
  Sources/App/Onboarding/Screens/OnboardingErrorView.swift
  Sources/App/Onboarding/Screens/OnboardingErrorViewController.swift
  Sources/App/Onboarding/Screens/OnboardingManualURLViewController.swift
  Sources/App/Onboarding/Screens/OnboardingPermissionViewController.swift
  Sources/App/Onboarding/Screens/OnboardingScanningViewController.swift
  Sources/App/Onboarding/Screens/OnboardingWelcomeView.swift
  Sources/App/Onboarding/Screens/OnboardingWelcomeViewController.swift
  Sources/App/Onboarding/Screens/SafariWebView.swift
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Eureka/SettingsButtonRow.swift
  Sources/Shared/Common/Extensions/XCGLogger+Export.swift
  Sources/Shared/Environment/Style.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed

#3056 Improve matter over thread error message
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Extensions/Matter/MatterRequestHandler.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, thread

#3055 Fix copy for iOS18 control switch
  Sources/Extensions/Widgets/Switch/ControlSwitchValueProvider.swift
Labels: cla-signed, widgets

#3057 Fix watch configuration values selection
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Shared/Common/Extensions/Color+hex.swift
  Sources/Shared/MagicItem/MagicItem.swift
Labels: cla-signed, watch

#3060 Use extended PAN ID instead of mac extended addres to select thread network
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Sources/Extensions/Matter/MatterRequestHandler.swift
  Sources/Shared/Settings/SettingsStore.swift
Labels: cla-signed, thread

#3059 Clear thread credentials before comissioning new matter device
  Sources/App/WebView/WebViewExternalMessageHandler.swift
Labels: cla-signed, thread

#3069 Avoid watch config 2024.9.3 migration issue
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRow.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Shared/Common/Extensions/GRDB+Initialization.swift
  Sources/Shared/MagicItem/MagicItem.swift
  Sources/Shared/Watch/WatchConfig.swift
  Tests/App/Watch/WatchConfig.test.swift
  Tests/App/Watch/WatchConfigV1.sqlite
Labels: bug, cla-signed, watch

#3073 Avoid nil icon color in watch config
  Sources/App/Settings/MagicItem/Edit/MagicItemCustomizationView.swift
Labels: cla-signed, watch

#3074 Add OHF logo to README
  README.md
Labels: cla-signed
