Repository home-assistant/iOS, pull requests merged in 2025-03, with the labels that each got.

#3468 Migrate LocationHistoryList to SwiftUI
  Gemfile.lock
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/ClientEvents/LocationHistoryDetailViewController.swift
  Sources/App/ClientEvents/LocationHistoryListView.swift
  Sources/App/ClientEvents/LocationHistoryListViewController.swift
  Sources/App/Settings/DebugView.swift
  Sources/App/Settings/SettingsDetailViewController.swift
  Sources/App/Utilities/Extensions/Array+SafeSubscripting.swift
  Sources/Shared/API/Models/LocationHistory.swift
  Tests/App/ClientEvents/LocationHistoryListViewSnapshot.test.swift
  Tests/App/ClientEvents/__Snapshots__/LocationHistoryListViewSnapshot.test/snapshotEmptyListTest.1.png
  Tests/App/ClientEvents/__Snapshots__/LocationHistoryListViewSnapshot.test/snapshotListTestWithContent.1.png
  Tests/App/Utilities/Extensions/Array+SafeSubscripting.test.swift
  Tests/App/Utilities/Extensions/UIColor+CSSRGB.test.swift
  Tests/Shared/ClientEventTests.swift
  fastlane/Fastfile
Labels: cla-signed

#3483 Add support to Assist stream response
  Sources/App/Assist/AssistViewModel.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Sources/Shared/Intents/AssistIntentHandler.swift
Labels: cla-signed, assist

#3481 Make custom widgets states not enabled by default
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Resources/en.lproj/Localizable.strings
  Sources/App/Settings/Widgets/Builder/WidgetBuilderView.swift
  Sources/App/Settings/Widgets/Builder/WidgetCreationView.swift
  Sources/App/Settings/Widgets/Builder/WidgetDocumentationLink.swift
  Sources/Extensions/Widgets/Custom/WidgetCustomTimelineProvider.swift
  Sources/Shared/DesignSystem/Components/ExternalLinkButton.swift
  Sources/Shared/ExternalLink.swift
  Sources/Shared/Resources/Swiftgen/Strings.swift
Labels: cla-signed, widgets

#3488 Assist continuous conversation listen directly after response if volume is 0
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/Assist/AssistViewModel.swift
  Sources/App/Assist/Audio/AudioPlayer.swift
  Sources/Shared/Common/Extensions/Float+HA.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistModel.swift
  Sources/Shared/Intents/AppIntent/AssistInApp/AssistService.swift
  Tests/App/Assist/AssistViewModel.test.swift
  Tests/App/Assist/Mocks/MockAssistService.swift
  Tests/App/Extensions/OptionalsDefaultTests.swift
Labels: cla-signed, assist

#3489 Add "triggerSource" to service calls
  Sources/App/Settings/ActionConfigurator.swift
  Sources/App/WatchCommunicatorService.swift
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/Extensions/AppIntents/Script/ScriptAppIntent.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Extensions/Widgets/Scene/SceneAppIntent.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/Models/Action.swift
  Sources/Shared/Intents/CallServiceIntentHandler.swift
Labels: cla-signed, watch, CarPlay, widgets, shortcuts

#3487 Create SharedTesting framework target
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/SharedTesting.xcscheme
  Podfile
  Podfile.lock
  Sources/Shared/Utilities/SnapshottablePreviewConfigurations.swift
  Sources/SharedTesting/SharedTesting.h
  Sources/SharedTesting/SnapshotTestingHelper.swift
  Sources/SharedTesting/SnapshottablePreviewConfigurations+SnapshotTesting.swift
  Tests/Widgets/WidgetsSnapshot.test.swift
  codecov.yaml
Labels: cla-signed

#3493 Revert "Create SharedTesting framework target"
  HomeAssistant.xcodeproj/project.pbxproj
  HomeAssistant.xcodeproj/xcshareddata/xcschemes/SharedTesting.xcscheme
  Podfile
  Podfile.lock
  Sources/Shared/Utilities/SnapshottablePreviewConfigurations.swift
  Sources/SharedTesting/SharedTesting.h
  Sources/SharedTesting/SnapshottablePreviewConfigurations+SnapshotTesting.swift
  Tests/App/SnapshotTestingHelper.swift
  Tests/Widgets/WidgetsSnapshot.test.swift
  codecov.yaml
Labels: cla-signed

#3492 Use navigation picker style for gestures picker to expand UI possibilities for more actions
  Sources/App/Settings/Gestures/GesturesSetupView.swift
Labels: cla-signed

#3490 Fix barcode scanner notify popup issue where it dismissed the scanner
  Sources/App/WebView/WebViewController.swift
  Sources/App/WebView/WebViewExternalMessageHandler.swift
  Tests/App/WebView/Mocks/MockWebViewController.swift
  Tests/App/WebView/WebViewExternalMessageHandlerTests.swift
Labels: cla-signed, barcode-scanner

#3501 Bump 2025.4
  Configuration/Version.xcconfig
Labels: cla-signed

#3505 Remove extra service data from call service request
  Sources/Shared/API/HAAPI.swift
Labels: cla-signed, shortcuts

#3506 Revert "Bump 2025.4"
  Configuration/Version.xcconfig
Labels: cla-signed

#3508 Include input_boolean to ControlSwitch for iOS 18+
  Sources/Extensions/Widgets/Controls/Switch/IntentSwitchEntity.swift
Labels: cla-signed, widgets, control-center

#3507 Move magic item execution out of API file
  HomeAssistant.xcodeproj/project.pbxproj
  Sources/App/WebView/IncomingURLHandler.swift
  Sources/CarPlay/Templates/QuickAccess/CarPlayQuickAccessTemplate.swift
  Sources/Extensions/Watch/Home/MagicItemRow/WatchMagicViewRowViewModel.swift
  Sources/Shared/API/AppTriggerSource.swift
  Sources/Shared/API/HAAPI.swift
  Sources/Shared/API/Models/Action.swift
  Sources/Shared/MagicItem/MagicItem.swift
Labels: cla-signed, watch, widgets, shortcuts
